#ifndef DESIGN_PATTERNS_SINGLETON_SINGLETON_HPP
#define DESIGN_PATTERNS_SINGLETON_SINGLETON_HPP

class Singleton {
public:

private:

}; // class Singleton

#endif // DESIGN_PATTERNS_SINGLETON_SINGLETON_HPP